version: '3.1'

services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: betinho
    ports:
      - "3306:3306"
    volumes:
      - $HOME/MySQLData/:/var/lib/mysql
    networks:
      - mysql-network
  backend:
    build: ./backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mysql-network
    env_file:
      - ./backend/dev.env
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
networks:
  mysql-network:
    driver: bridge