# Generated by Django 4.0.4 on 2022-05-27 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('location', models.TextField()),
                ('result', models.IntegerField(choices=[(1, 'Home Win'), (2, 'Draw'), (3, 'Away Win')], null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BETinho.teammodel')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BETinho.teammodel')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='BetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('result', models.IntegerField(choices=[(1, 'Home Win'), (2, 'Draw'), (3, 'Away Win')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BETinho.eventmodel')),
            ],
            options={
                'db_table': 'bet',
            },
        ),
    ]
