name: Continuous integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install coverage
      - name: Run backend unit tests
        run: python -m unittest discover -s backend

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install coverage
      - name: Run backend unit tests with coverage
        run: coverage run --source backend/BETinho -m unittest discover -s backend
      - name: Generate coverage xml report
        run: coverage xml --rcfile=backend/.coveragerc
      - name: Show raw coverage report
        run: coverage report --rcfile=backend/.coveragerc
      - uses: codecov/codecov-action@v2
        with:
          files: "coverage.xml"
          fail_ci_if_error: true
          verbose: true
